version: '3.8'

services:
  ml-api-instance-1:
    image: ml-api
    build:
      context: ./app
    ports:
      - "5001:5000"

  ml-api-instance-2:
    image: ml-api
    build:
      context: ./app
    ports:
      - "5002:5000"

  nginx-load-balancer:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - ml-api-instance-1
      - ml-api-instance-2
